### ISSUE TITLE
Unable to Make

### ISSUE THREAD

**Issue by PR-Iyyer** [hongxinliu/edge-drawing#1]
> mkdir -p build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=. && make && make install
-- Configuring done
-- Generating done
-- Build files have been written to: /data/binil/BPY/Praveena_1/SWT/edge-drawing/build
make[1]: Entering directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[2]: Entering directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[3]: Entering directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[3]: Leaving directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[3]: Entering directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
[ 25%] Building CXX object CMakeFiles/ed.dir/src/ed.cpp.o
In file included from /data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:7:0:
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:17: error: ‘list’ is not a member of ‘std’
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                 ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:17: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:31: error: template argument 1 is invalid
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                               ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:31: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:36: error: expected unqualified-id before ‘>’ token
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                                    ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:51:17: error: ‘list’ is not a member of ‘std’
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                 ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:51:17: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:51:31: error: template argument 1 is invalid
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                               ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:51:31: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:51:36: error: expected unqualified-id before ‘>’ token
     std::vector<std::list<cv::Point>> detectEdges(const cv::Mat &image,
                                    ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
                          std::vector<std::list<cv::Point>> &edges);
                                      ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:52: error: template argument 1 is invalid
                          std::vector<std::list<cv::Point>> &edges);
                                                    ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:52: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
                          std::vector<std::list<cv::Point>> &edges);
                                      ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 1 is invalid
                          std::vector<std::list<cv::Point>> &edges);
                                                         ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
                          std::vector<std::list<cv::Point>> &edges);
                                      ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 1 is invalid
                          std::vector<std::list<cv::Point>> &edges);
                                                         ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
                          std::vector<std::list<cv::Point>> &edges);
                                      ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 1 is invalid
                          std::vector<std::list<cv::Point>> &edges);
                                                         ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
                          std::vector<std::list<cv::Point>> &edges);
                                      ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:38: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 1 is invalid
                          std::vector<std::list<cv::Point>> &edges);
                                                         ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:57: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:31: error: ‘std::vector’ is not a type
                          std::vector<std::list<cv::Point>> &edges);
                               ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:96:37: error: expected ‘,’ or ‘...’ before ‘<’ token
                          std::vector<std::list<cv::Point>> &edges);
                                     ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:117:21: error: ‘std::list’ has not been declared
                std::list<cv::Point> &edge);
                     ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:117:25: error: expected ‘,’ or ‘...’ before ‘<’ token
                std::list<cv::Point> &edge);
                         ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:120:13: error: ‘list’ is not a member of ‘std’
 std::vector<std::list<cv::Point>> ED_Internal::detectEdges(const cv::Mat &image,
             ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:120:13: error: ‘list’ is not a member of ‘std’
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:120:27: error: template argument 1 is invalid
 std::vector<std::list<cv::Point>> ED_Internal::detectEdges(const cv::Mat &image,
                           ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:120:27: error: template argument 2 is invalid
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:120:32: error: expected unqualified-id before ‘>’ token
 std::vector<std::list<cv::Point>> ED_Internal::detectEdges(const cv::Mat &image,
                                ^
/data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:441:1: error: expected ‘}’ at end of input
 }
 ^
make[3]: *** [CMakeFiles/ed.dir/src/ed.cpp.o] Error 1
make[3]: Leaving directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[2]: *** [CMakeFiles/ed.dir/all] Error 2
make[2]: Leaving directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/data/binil/BPY/Praveena_1/SWT/edge-drawing/build'
make: *** [all] Error 2

Please Help.. What could be wrong?

**Comment by hongxinliu** [comment]
According to the error "In file included from /data/binil/BPY/Praveena_1/SWT/edge-drawing/src/ed.cpp:7:0:
/data/binil/BPY/Praveena_1/SWT/edge-drawing/./include/ed.hpp:27:17: error: ‘list’ is not a member of ‘std’", compiler can not see definition of std::list. 

I did not include "list" header cause it is included by "opencv2/opencv.hpp" on macOS and Ubuntu, but may not in other OS.

I have updated header included, please pull the newest code and try again.

**Comment by PR-Iyyer** [comment]
thank u..!
